### ISSUE TITLE
Unable to determine github branch

### ISSUE THREAD

**Issue by jameskyle** [ejoffe/spr#346]
Looks like spr is defaulting to `origin/main` though this branch does not exist in my project.

```
git spr status
error: unable to fetch remote branch info, using defaults> git rev-parse --show-toplevel
> github fetch pull requests
> git log --format=medium --no-color origin/main..HEAD
git error: fatal: ambiguous argument 'origin/main..HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
panic: exit status 128
```

**Comment by ejoffe** [comment]
To solve this you can either set the upstream for your branch or update the .spr.yml in your repo to point to the correct upstream branch.

**Comment by alexmirrington** [comment]
@ejoffe Been running into the same issue since v0.13.0. Adding the following to `.spr.yml` does not fix the issue, as the config seems to get re-written on when running `git spr s`:

```
githubRemote: origin
githubBranch: master
```

**Comment by jameskyle** [comment]
+1 on config being rewritten.

**Comment by ejoffe** [comment]
fixed in v0.14.1

**Comment by jameskyle** [comment]
I'm still seeing this issue, though it no longer overwrites the config.

* remote/branch set in config
* set the upstream branch to my target branch `develop`
* verified v0.14.1

```
❯ egrep "githubRemote|githubBranch" .spr.yml
githubRemote: origin
githubBranch: develop
❯ ls -l $(which git-spr)
lrwxr-xr-x@ 1 jkyle  admin  32 Aug  8 11:19 /usr/local/bin/git-spr -> ../Cellar/spr/0.14.1/bin/git-spr
❯ git branch -vv | grep 658
* ef-658-customer-config-filtering-features        5e6c0e3a0a [develop: ahead 1] ef-660: add code coverage to effected methods
❯ git spr update
error: unable to fetch remote branch info, using defaults> git rev-parse --show-toplevel
> git fetch
> git rebase origin/main --autostash
git error: fatal: invalid upstream 'origin/main'
```

**Comment by jameskyle** [comment]
I don't think I can reopen this, filing new bug.
